# Generated by Django 6.0.7 on 2026-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.BooleanField(default=False, verbose_name='Concluída')),
                ('priority', models.CharField(choices=[('L', 'Baixa'), ('M', 'Média'), ('H', 'Alta')], default='M', max_length=1, verbose_name='Prioridade')),
                ('start_time', models.DateTimeField(verbose_name='Data de Início')),
                ('due_date', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Lembrete Enviado')),
            ],
        ),
    ]
