# Generated by Django 6.0.7 on 2026-07-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('iniciado', 'Iniciado'), ('pendente', 'Pendente'), ('concluido', 'Concluído'), ('atrasado', 'Atrasado')], default='nao_iniciado', max_length=20, verbose_name='Status'),
        ),
    ]
